services:
  caisse-staging-db:
    image: postgres:15
    container_name: caisse_staging_db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pg_caisse_data_staging:/var/lib/postgresql/data
    env_file:
      - ./apis/.env.db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "caisse_staging"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 30s
    networks:
      - caisse_network

  caisse-staging-apis:
    build:
      context: ./apis
      dockerfile: Dockerfile
    container_name: caisse_staging_apis
    restart: "no"
    ports:
      - "3344:3333"
    depends_on:
      caisse-staging-db:
        condition: service_healthy
    env_file:
      - ./apis/.env
    networks:
      - caisse_network
    #command: ["sh", "-c", "node ace migration:run --force && node bin/server.js"]
    volumes:
      - /var/lib/caisse-staging/uploads:/app/uploads
      - /var/lib/caisse-staging/public:/app/public


  caisse-staging-apps:
    build:
      context: ./apps
      dockerfile: Dockerfile
    container_name: caisse_staging_apps
    image: caisse-staging-apps:latest
    restart: always
    ports:
      - "82:80"
    networks:
      - caisse_network
    depends_on:
      - caisse-staging-apis
      
  caisse-staging-backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    container_name: caisse_staging_backoffice
    image: caisse-staging-backoffice:latest
    restart: always
    ports:
      - "84:80"
    networks:
      - caisse_network
    depends_on:
      - caisse-staging-apis

volumes:
  pg_caisse_data_staging:

networks:
  caisse_network:
    driver: bridge
